### ISSUE TITLE
About file structures of this project

### ISSUE THREAD

**Issue by pmh-only** [GBSWHS/codenest#2]
Ok, I think separating frontend and backend code via branches is not a good idea.
Github just goes "bro, wtf man.. frontend is N commits before main branch" like this:
![image](https://github.com/GBSWHS/codenest/assets/39158228/ce49ad62-d36b-4aac-8a95-d9a2de8152e5)

You know, it sucks.

Is there any plan to use some common structures like monorepo or multirepo?
Thanks.

**Comment by wHoIsDReAmer** [comment]
the branch would be merged at main branch. not keeping this structure.

**Comment by wHoIsDReAmer** [comment]
or is there better way to manage repo? if it, present the way pls

**Comment by pmh-only** [comment]
There are some recommended structures for this:
* monorepo (ex: https://github.com/pmh-only/guess-ai-word)
* multirepo (ex: https://github.com/gbswhs/awsmgr-backend, https://github.com/gbswhs/awsmgr-frontend)

also, some management softwares are exist. like [yarn berry](https://yarnpkg.com/features/workspaces) or [tuborepo](https://turbo.build/repo)
but you know, using repo manager can be over-engineering.

I think [git submodule feature](https://github.blog/2016-02-01-working-with-submodules/), the "repo-in-repo", is light-weight and very nice way to do this.

**Comment by wHoIsDReAmer** [comment]
nice! i will refer your presenting, called "repo-in-repo". have a good day
